#CSCI 340
#JUSTIN ROESNER
#z1858242
#ASSIGNMENT 5 MAKEFILE
#DUE 3-15-19

CXX=g++
CXXFLAGS=-Wall -g

assignment5 : assignment5.cc
	$(CXX) $(CXXFLAGS) assignment5.cc -o assignment5.exe



# to test run  ./assignment5.exe &> assignment5.out
