#CSCI 340
#JUSTIN ROESNER
#z1858242
#ASSIGNMENT 5 MAKEFILE
#DUE 3-15-19

CXX=g++
CXXFLAGS=-Wall 

assignment6 : assignment6.cc
	$(CXX) $(CXXFLAGS) assignment5.cc assignment6.cc assignment6main.cc -o assignment6.exe



# to test run	 ./assignment6.exe &> assignment6.out
