#CSCI 340
#JUSTIN ROESNER
#z1858242
#ASSIGNMENT 3 MAKEFILE
#DUE 2-15-2019

CXX=g++
CXXFLAGS=-Wall -g

assignment3 : assignment3.cc
	$(CXX) $(CXXFLAGS) assignment3.cc -o assignment3.exe


#to test use "./assignment3.exe < assigment3input.txt &> assignment3.out"
