#CSCI 340
#JUSTIN ROESNER
#z1858242
#ASSIGNMENT 4 MAKEFILE
#DUE 2-26-19

CXX=g++
CXXFLAGS=-Wall -g

assignment4 : assignment4.cc
	$(CXX) $(CXXFLAGS) assignment4.cc -o assignment4.exe




#to text execute ./assignment4.exe < assignment4input.txt > assigment4.out 2>&1
